# -*- coding: utf-8 -*-
"""grokking project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V4lkakcR1w6d7f9DpnxCaiIsSv_s-K9z
"""

"""
=============================================================================
  Grokking of Modular Arithmetic — Full Mechanistic Interpretability Suite
=============================================================================
Parts implemented:
  1. Grokking curves: accuracy + loss (distinct prime, blue=train, red=test)
  2. Fourier analysis: 1D DFT of embeddings & MLP neurons → sparse frequencies
  3. Three-phase decomposition: Memorisation → Circuit Formation → Cleanup
  4. Data-fraction sweep: Epochs-until-generalisation vs. training fraction
  5. Algorithm reverse-engineering: what the model learns for (a × b) mod p
  6. Co-grokking: multi-task addition + multiplication grok simultaneously

GPU auto-detected (CUDA). Falls back to CPU gracefully.
All figures saved to  ./grokking_output/  as high-res PNGs.

Usage:
    python grokking.py                  # default config
    python grokking.py --epochs 20000    # longer training
    python grokking.py --p 89            # different prime
=============================================================================
"""

import os, sys, math, time, random, argparse
from pathlib import Path

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.patches import Patch

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import einops

# ─────────────────────────────────────────────────────────────────────────────
#  CLI CONFIG
# ─────────────────────────────────────────────────────────────────────────────

def get_config():
    p = argparse.ArgumentParser(description="Grokking Analysis")
    p.add_argument("--p",           type=int,   default=67,     help="Prime modulus (default 67, ≠ 113)")
    p.add_argument("--epochs",      type=int,   default=25000,  help="Training epochs — 25k mirrors Nanda et al. (grokking ~10-18k for p=67)")
    p.add_argument("--sweep_epochs",type=int,   default=15000,  help="Epochs per fraction-sweep model")
    p.add_argument("--frac",        type=float, default=0.30,   help="Training data fraction — 0.30 matches Nanda et al. canonical setup")
    p.add_argument("--lr",          type=float, default=1e-3,   help="Learning rate")
    p.add_argument("--wd",          type=float, default=0.7,    help="Weight decay (L2) — 0.7 tuned for p=67 to grok ~12k epochs (paper: 1.0 for p=113)")
    p.add_argument("--d_model",     type=int,   default=128,    help="Embedding dimension")
    p.add_argument("--seed",        type=int,   default=42,     help="Random seed")
    p.add_argument("--outdir",      type=str,   default="grokking_output", help="Output directory")
    p.add_argument("--no_amp",      action="store_true",        help="Disable AMP (mixed precision)")
    # ── Co-Grokking specific args ──────────────────────────────────────────────
    # ROOT CAUSE OF NON-GROKKING: wd must be HIGHER than single-task, not lower.
    # With low wd (e.g. 0.1), the model happily memorises both tasks and the
    # weight-decay pressure is insufficient to drive either circuit to generalise.
    # Mechanism: memorisation needs large weights; high wd makes large weights
    # expensive; the model's only escape is the compact Fourier generalisation circuit.
    # With wd=1.5 (2x single-task wd=0.7), both circuits are forced to generalise.

    p.add_argument("--cogrok_wd",     type=float, default=1.5,
                   help="Weight decay for co-grokking. Needs wd=3.0+ to force cleanup phase. "
                        "Too low (< 2.0) leaves model stuck in memorisation forever.")
    p.add_argument("--cogrok_frac",   type=float, default=0.40,
                   help="Train-data fraction for co-grokking — 0.6 needed for dual-circuit to beat memorisation")
    p.add_argument("--cogrok_d_model", type=int,   default=256,
                   help="Embedding dim for co-grokking — 256 gives each task ~128 dims, same as single-task alone")
    p.add_argument("--cogrok_lr",      type=float, default=1e-3,
                   help="Learning rate for co-grokking — lower than single-task to prevent oscillations")
    p.add_argument("--cogrok_epochs",  type=int,   default=50000,
                   help="Epochs for co-grokking — 300k needed for two circuits")
    args, _ = p.parse_known_args()
    return args

# ─────────────────────────────────────────────────────────────────────────────
#  DEVICE
# ─────────────────────────────────────────────────────────────────────────────

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def print_device():
    if DEVICE.type == "cuda":
        props = torch.cuda.get_device_properties(0)
        mem   = props.total_memory / 1e9
        print(f"  GPU : {props.name}  ({mem:.1f} GB VRAM)")
    else:
        print("  CPU (no CUDA found — training will be slower)")

# ─────────────────────────────────────────────────────────────────────────────
#  COLOUR PALETTE + PLOT HELPERS
# ─────────────────────────────────────────────────────────────────────────────

BG   = "#080814"
CARD = "#12122a"
LINE = "#252545"
TXT  = "#cbd5e1"

C_TR  = "#60a5fa"   # training   – blue  (matches reference diagram)
C_TE  = "#f87171"   # validation – red
C_WN  = "#34d399"   # weight norm
C_MUL = "#fbbf24"   # multiplication task
C_PUR = "#a78bfa"   # grokking annotation

PHASE_COLS = [
    ("#1a2040", "#60a5fa", "① Memorisation"),
    ("#162018", "#34d399", "② Circuit Formation"),
    ("#200f30", "#a78bfa", "③ Cleanup"),
]


def new_fig(*args, **kwargs):
    fig = plt.figure(*args, facecolor=BG, **kwargs)
    return fig


def style_ax(ax, title="", xlabel="", ylabel=""):
    ax.set_facecolor(CARD)
    ax.tick_params(colors=TXT, labelsize=8.5)
    for sp in ax.spines.values():
        sp.set_color(LINE)
    ax.xaxis.label.set_color(TXT)
    ax.yaxis.label.set_color(TXT)
    ax.title.set_color("#c7d2fe")
    ax.grid(True, alpha=0.15, color=LINE, lw=0.6)
    if title:   ax.set_title(title,  pad=7, fontsize=10)
    if xlabel:  ax.set_xlabel(xlabel)
    if ylabel:  ax.set_ylabel(ylabel)


def savefig(fig, path):
    plt.tight_layout(pad=1.4)
    fig.savefig(path, dpi=150, bbox_inches="tight", facecolor=BG)
    plt.close(fig)
    print(f"    Saved → {path}")


# ─────────────────────────────────────────────────────────────────────────────
#  NUMBER-THEORY HELPERS
# ─────────────────────────────────────────────────────────────────────────────

def prime_factors(n):
    fs, d = set(), 2
    while d * d <= n:
        while n % d == 0:
            fs.add(d); n //= d
        d += 1
    if n > 1: fs.add(n)
    return fs


def primitive_root(p):
    phi  = p - 1
    facs = prime_factors(phi)
    for g in range(2, p):
        if all(pow(g, phi // f, p) != 1 for f in facs):
            return g
    return 2


def discrete_log_table(p, g):
    """Returns dict: a → k  s.t.  g^k ≡ a (mod p),  for a in 1..p-1."""
    table, cur = {}, 1
    for k in range(p - 1):
        table[cur] = k
        cur = (cur * g) % p
    return table


# ─────────────────────────────────────────────────────────────────────────────
#  DATASET HELPERS
# ─────────────────────────────────────────────────────────────────────────────

OP_ADD = "add"   # input op-token = p
OP_MUL = "mul"   # input op-token = p+1

def op_token(p, op):
    return p if op == OP_ADD else p + 1


def make_dataset(p, op):
    """List of (a, op_tok, b, label)."""
    tok  = op_token(p, op)
    data = []
    for a in range(p):
        for b in range(p):
            lbl = (a + b) % p if op == OP_ADD else (a * b) % p
            data.append((a, tok, b, lbl))
    return data


def make_dataset_mul_nonzero(p):
    """
    Multiplication dataset using only nonzero operands: a, b in 1..p-1.

    WHY THIS IS THE ROOT CAUSE OF NON-GROKKING
    ───────────────────────────────────────────
    For a prime p, the multiplicative group (Z_p*, x) is cyclic of order p-1.
    The model generalises multiplication via the discrete-log isomorphism:
        (Z_p*, x)  ~=  (Z_{p-1}, +)  via  a  |->  ind_g(a)
    and then applies the same Fourier-rotation algorithm used for addition.

    When (a=0) or (b=0) pairs are in the dataset, the label is always 0.
    But 0 has NO discrete log and does NOT belong to Z_p*. The model cannot
    handle these pairs with the clean Fourier circuit — it must keep a separate
    memorised lookup for zeros. That lookup raises the weight norm of the
    "generalising" solution above pure memorisation, so weight decay can NEVER
    trigger the cleanup phase. Result: multiplication never groks, regardless
    of how many epochs you train or how high you set wd.

    Excluding zero pairs fixes this: every example fits the discrete-log
    algorithm, the generalising solution has strictly lower weight norm than
    memorisation, weight decay triggers cleanup, both tasks grok.

    Note: for prime p, (a * b) % p != 0 whenever a, b != 0 (no zero divisors),
    so all labels are also in 1..p-1 — fully compatible with the model output.
    """
    tok  = op_token(p, OP_MUL)
    data = []
    for a in range(1, p):          # exclude 0
        for b in range(1, p):      # exclude 0
            lbl = (a * b) % p      # always in 1..p-1 for prime p
            data.append((a, tok, b, lbl))
    return data


def split_dataset(data, frac_train, seed):
    data = list(data)
    random.seed(seed)
    random.shuffle(data)
    div = int(frac_train * len(data))
    return data[:div], data[div:]


def to_tensors(data, device):
    inp = torch.tensor([[a, op, b] for a, op, b, _ in data],
                       dtype=torch.long, device=device)
    lbl = torch.tensor([lbl for *_, lbl in data],
                       dtype=torch.long, device=device)
    return inp, lbl


# ─────────────────────────────────────────────────────────────────────────────
#  MODEL  (one-layer transformer, faithful to Nanda et al. 2023)
# ─────────────────────────────────────────────────────────────────────────────

class Embed(nn.Module):
    def __init__(self, d_vocab, d_model):
        super().__init__()
        self.W_E = nn.Parameter(torch.randn(d_model, d_vocab) / math.sqrt(d_model))
    def forward(self, x):
        return einops.rearrange(self.W_E[:, x], "d b s -> b s d")


class Unembed(nn.Module):
    def __init__(self, d_vocab, d_model):
        super().__init__()
        self.W_U = nn.Parameter(torch.randn(d_model, d_vocab) / math.sqrt(d_vocab))
    def forward(self, x):
        return x @ self.W_U


class PosEmbed(nn.Module):
    def __init__(self, max_ctx, d_model):
        super().__init__()
        self.W_pos = nn.Parameter(torch.randn(max_ctx, d_model) / math.sqrt(d_model))
    def forward(self, x):
        return x + self.W_pos[: x.shape[-2]]


class Attention(nn.Module):
    def __init__(self, d_model, n_heads, d_head, n_ctx):
        super().__init__()
        self.W_K = nn.Parameter(torch.randn(n_heads, d_head, d_model) / math.sqrt(d_model))
        self.W_Q = nn.Parameter(torch.randn(n_heads, d_head, d_model) / math.sqrt(d_model))
        self.W_V = nn.Parameter(torch.randn(n_heads, d_head, d_model) / math.sqrt(d_model))
        self.W_O = nn.Parameter(torch.randn(d_model, d_head * n_heads) / math.sqrt(d_model))
        self.register_buffer("mask", torch.tril(torch.ones(n_ctx, n_ctx)))
        self.d_head = d_head
        # LayerNorm removed — paper uses no LN (Nanda et al. 2023)

    def forward(self, x):
        k   = torch.einsum("ihd,bpd->biph", self.W_K, x)
        q   = torch.einsum("ihd,bpd->biph", self.W_Q, x)
        v   = torch.einsum("ihd,bpd->biph", self.W_V, x)
        sc  = torch.einsum("biph,biqh->biqp", k, q)
        sc  = sc - 1e10 * (1 - self.mask[: x.shape[-2], : x.shape[-2]])
        attn= F.softmax(sc / math.sqrt(self.d_head), dim=-1)
        z   = torch.einsum("biph,biqp->biqh", v, attn)
        return torch.einsum("df,bqf->bqd", self.W_O,
                            einops.rearrange(z, "b i q h -> b q (i h)"))


class MLP(nn.Module):
    def __init__(self, d_model, d_mlp):
        super().__init__()
        # LayerNorm removed — paper uses no LN (Nanda et al. 2023)
        self.W_in  = nn.Parameter(torch.randn(d_mlp, d_model) / math.sqrt(d_model))
        self.b_in  = nn.Parameter(torch.zeros(d_mlp))
        self.W_out = nn.Parameter(torch.randn(d_model, d_mlp) / math.sqrt(d_model))
        self.b_out = nn.Parameter(torch.zeros(d_model))
        self._post = None   # cached for DFT analysis

    def forward(self, x):
        pre = torch.einsum("md,bpd->bpm", self.W_in, x) + self.b_in
        post = F.relu(pre)
        self._post = post.detach()
        return torch.einsum("dm,bpm->bpd", self.W_out, post) + self.b_out


class Transformer(nn.Module):
    """
    Input:  [a, op_token, b]   (seq length 3)
    Output: logits over d_vocab, predict at position 2
    d_vocab = p + 2  (tokens 0..p-1 are numbers; p = '+' token; p+1 = '×' token)
    """
    def __init__(self, p, d_model=128, n_heads=4, n_ctx=3):
        super().__init__()
        d_vocab = p + 2
        d_head  = d_model // n_heads
        self.p  = p
        self.embed     = Embed(d_vocab, d_model)
        self.pos_embed = PosEmbed(n_ctx, d_model)
        self.attn      = Attention(d_model, n_heads, d_head, n_ctx)
        self.mlp       = MLP(d_model, 4 * d_model)
        self.unembed   = Unembed(d_vocab, d_model)
        # ln_out removed — paper uses no LN (Nanda et al. 2023)

    def forward(self, x):
        h = self.embed(x)
        h = self.pos_embed(h)
        h = h + self.attn(h)
        h = h + self.mlp(h)
        return self.unembed(h)  # no final LayerNorm — matches Nanda et al.

    # ── analysis helpers ──────────────────────────────────────────────────────

    @property
    def W_E_np(self):
        """Token embedding matrix, rows = tokens 0..p-1.  Shape (p, d_model)."""
        return self.embed.W_E.detach().T[: self.p].float().cpu().numpy()

    def get_mlp_activations(self, inp):
        """Run forward, return post-ReLU MLP acts at last position.  (N, d_mlp)."""
        self.eval()
        with torch.no_grad():
            self.forward(inp)
        return self.mlp._post[:, -1, :].float().cpu().numpy()


def _raw(model):
    """Unwrap torch.compile wrapper if present."""
    return getattr(model, "_orig_mod", model)


# ─────────────────────────────────────────────────────────────────────────────
#  TRAINING UTILITIES
# ─────────────────────────────────────────────────────────────────────────────

def cross_entropy(logits, labels):
    """High-precision cross-entropy (float64 log-softmax)."""
    lp = F.log_softmax(logits.double(), dim=-1)
    return -torch.gather(lp, 1, labels[:, None]).mean()


def accuracy(logits, labels):
    return (logits.argmax(-1) == labels).float().mean().item()


def weight_norm_sq(model):
    return sum(p.detach().float().pow(2).sum().item() for p in model.parameters())


def constant_lr(step, warmup, base_lr):
    """Linear warmup for `warmup` steps, then constant LR — matches Nanda et al. 2023.
    The paper uses LambdaLR(opt, lambda step: min(step/10, 1)).
    """
    return base_lr * min(step / max(warmup, 1), 1.0)


def build_model(p, d_model, device, compile_model=True):
    m = Transformer(p=p, d_model=d_model).to(device)
    if compile_model and device.type == "cuda":
        try:
            # "default" compiles without CUDA Graphs, avoiding the
            # "overwritten tensor output" RuntimeError that "reduce-overhead"
            # triggers when the model is called multiple times per training step.
            m = torch.compile(m, mode="default")
            print("    torch.compile enabled (mode=default)")
        except Exception:
            pass
    return m


# ─────────────────────────────────────────────────────────────────────────────
#  SINGLE-TASK TRAINING
# ─────────────────────────────────────────────────────────────────────────────

def train(p, op, frac_train, epochs, lr, wd, d_model, seed, device,
          use_amp=True, log_every=50, label=""):
    """
    Full-batch training on one operation.
    Returns dict with all metrics + trained model.
    """
    tag = label or f"(a {'+ ' if op==OP_ADD else '× '} b) mod {p}"
    print(f"\n  Training {tag}  [{epochs:,} epochs, device={device}]")

    # ── data ────────────────────────────────────────────────────────────────
    train_data, test_data = split_dataset(make_dataset(p, op), frac_train, seed)
    tr_inp, tr_lbl = to_tensors(train_data, device)
    te_inp, te_lbl = to_tensors(test_data,  device)

    # ── model ───────────────────────────────────────────────────────────────
    model  = build_model(p, d_model, device)
    opt    = optim.AdamW(model.parameters(), lr=lr, weight_decay=wd,
                         betas=(0.9, 0.98), eps=1e-8)
    scaler = torch.amp.GradScaler() if (device.type == "cuda" and use_amp) else None
    warmup = 500  # longer warmup — prevents early spikes with cogrok_lr=5e-4

    # ── metric buffers ───────────────────────────────────────────────────────
    tr_losses, te_losses = [], []
    tr_accs,   te_accs   = [], []
    w_norms,   ckpts     = [], []

    t0 = time.time()
    for ep in range(epochs + 1):

        # ── log ─────────────────────────────────────────────────────────────
        if ep % log_every == 0:
            model.eval()
            with torch.no_grad():
                tr_lg = model(tr_inp)[:, -1]
                te_lg = model(te_inp)[:, -1]
            trl = cross_entropy(tr_lg, tr_lbl).item()
            tel = cross_entropy(te_lg, te_lbl).item()
            tra = accuracy(tr_lg, tr_lbl)
            tea = accuracy(te_lg, te_lbl)
            wn  = weight_norm_sq(model)
            tr_losses.append(trl); te_losses.append(tel)
            tr_accs.append(tra);   te_accs.append(tea)
            w_norms.append(wn);    ckpts.append(ep)

            if ep % (log_every * 10) == 0:
                elapsed = time.time() - t0
                eta     = elapsed / max(ep, 1) * (epochs - ep)
                print(f"    ep {ep:>7,}/{epochs:,} | "
                      f"train {tra:.1%}  test {tea:.1%} | "
                      f"loss {trl:.3f}/{tel:.3f} | "
                      f"{elapsed:.0f}s  ETA {eta:.0f}s")

        if ep == epochs:
            break

        # ── gradient step ────────────────────────────────────────────────────
        new_lr = constant_lr(ep, warmup, lr)
        for g in opt.param_groups:
            g["lr"] = new_lr

        model.train()
        if scaler:
            with torch.amp.autocast(device_type="cuda"):
                loss = cross_entropy(model(tr_inp)[:, -1], tr_lbl)
            scaler.scale(loss).backward()
            scaler.unscale_(opt)
            # grad clipping removed — paper uses no clipping
            scaler.step(opt); scaler.update()
        else:
            loss = cross_entropy(model(tr_inp)[:, -1], tr_lbl)
            loss.backward()
            # grad clipping removed — paper uses no clipping
            opt.step()
        opt.zero_grad(set_to_none=True)

    elapsed = time.time() - t0
    print(f"    Done in {elapsed:.1f}s  |  "
          f"final train {tr_accs[-1]:.1%}  test {te_accs[-1]:.1%}")

    return {
        "model":        model,
        "p":            p,
        "op":           op,
        "train_data":   train_data,
        "test_data":    test_data,
        "tr_losses":    np.array(tr_losses),
        "te_losses":    np.array(te_losses),
        "tr_accs":      np.array(tr_accs),
        "te_accs":      np.array(te_accs),
        "w_norms":      np.array(w_norms),
        "epochs":       np.array(ckpts),
        "elapsed":      elapsed,
    }


# ─────────────────────────────────────────────────────────────────────────────
#  CO-GROKKING  (multi-task: addition + multiplication)
# ─────────────────────────────────────────────────────────────────────────────

def train_multitask(p, frac_train_add, frac_train_mul, epochs, lr, wd, d_model, seed, device,
                    use_amp=True, log_every=50):
    """
    Single model trained simultaneously on addition AND multiplication.

    THREE ROOT CAUSES of non-grokking (all fixed here):

    1. ZERO PAIRS IN MULTIPLICATION  ← critical root cause
       Pairs (a=0,*) or (*,b=0) always give label 0, have no discrete log,
       and cannot be solved by the Fourier circuit. The model keeps a separate
       memorised lookup for them, raising the weight norm of the "generalising"
       solution above pure memorisation. Weight decay never triggers cleanup.
       FIX: use make_dataset_mul_nonzero() — only a,b in 1..p-1.

    2. INSUFFICIENT WEIGHT DECAY
       With two tasks, the memorisation manifold is 2x larger. wd=1.5 does not
       create enough pressure; wd=3.0 does.

    3. GRADIENT IMBALANCE
       One combined shuffled batch mixes gradients. If tasks differ in difficulty
       the easier one dominates. Separate per-task losses fix this.
    """
    print(f"\n  Co-Grokking (Add + Mul)  [{epochs:,} epochs, wd={wd}, device={device}]")
    print(f"  KEY FIX 1: multiplication uses nonzero pairs only (zeros broke grokking)")
    print(f"  KEY FIX 2: separate per-task losses → balanced gradient signal")
    print(f"  KEY FIX 3: wd={wd} (needs >= 2.5 to force dual cleanup)")
    print(f"  Grokking expected: ~40,000-120,000 epochs with wd={wd}")

    # Addition: full dataset (zero is the identity element, fits Fourier alg)
    add_tr, add_te = split_dataset(make_dataset(p, OP_ADD), frac_train_add, seed)

    # Multiplication: NONZERO pairs only — fixes root cause of non-grokking
    mul_tr, mul_te = split_dataset(make_dataset_mul_nonzero(p), frac_train_mul, seed + 1)

    add_tr_inp, add_tr_lbl = to_tensors(add_tr, device)
    add_te_inp, add_te_lbl = to_tensors(add_te, device)
    mul_tr_inp, mul_tr_lbl = to_tensors(mul_tr, device)
    mul_te_inp, mul_te_lbl = to_tensors(mul_te, device)

    model  = build_model(p, d_model, device)
    opt    = optim.AdamW(model.parameters(), lr=lr, weight_decay=wd,
                         betas=(0.9, 0.98), eps=1e-8)
    scaler = torch.amp.GradScaler() if (device.type == "cuda" and use_amp) else None
    warmup = 500  # longer warmup — prevents early spikes with cogrok_lr=5e-4

    add_tr_ls, add_te_ls = [], []
    add_tr_as, add_te_as = [], []
    mul_tr_ls, mul_te_ls = [], []
    mul_tr_as, mul_te_as = [], []
    w_norms, ckpts       = [], []

    t0 = time.time()
    for ep in range(epochs + 1):

        if ep % log_every == 0:
            model.eval()
            with torch.no_grad():
                a_tlg = model(add_tr_inp)[:, -1]
                a_elg = model(add_te_inp)[:, -1]
                m_tlg = model(mul_tr_inp)[:, -1]
                m_elg = model(mul_te_inp)[:, -1]

            add_tr_ls.append(cross_entropy(a_tlg, add_tr_lbl).item())
            add_te_ls.append(cross_entropy(a_elg, add_te_lbl).item())
            add_tr_as.append(accuracy(a_tlg, add_tr_lbl))
            add_te_as.append(accuracy(a_elg, add_te_lbl))
            mul_tr_ls.append(cross_entropy(m_tlg, mul_tr_lbl).item())
            mul_te_ls.append(cross_entropy(m_elg, mul_te_lbl).item())
            mul_tr_as.append(accuracy(m_tlg, mul_tr_lbl))
            mul_te_as.append(accuracy(m_elg, mul_te_lbl))
            w_norms.append(weight_norm_sq(model))
            ckpts.append(ep)

            if ep % (log_every * 10) == 0:
                elapsed = time.time() - t0
                eta     = elapsed / max(ep, 1) * (epochs - ep)
                print(f"    ep {ep:>7,}/{epochs:,} | "
                      f"add {add_te_as[-1]:.1%}  mul {mul_te_as[-1]:.1%} | "
                      f"{elapsed:.0f}s  ETA {eta:.0f}s")

        if ep == epochs:
            break

        new_lr = constant_lr(ep, warmup, lr)
        for g in opt.param_groups:
            g["lr"] = new_lr

        model.train()
        # KEY FIX: compute each task loss separately → equal gradient signal
        if scaler:
            with torch.amp.autocast(device_type="cuda"):
                add_loss = cross_entropy(model(add_tr_inp)[:, -1], add_tr_lbl)
                mul_loss = cross_entropy(model(mul_tr_inp)[:, -1], mul_tr_lbl)
                loss = add_loss + mul_loss
            scaler.scale(loss).backward()
            scaler.unscale_(opt)
            scaler.step(opt); scaler.update()
        else:
            add_loss = cross_entropy(model(add_tr_inp)[:, -1], add_tr_lbl)
            mul_loss = cross_entropy(model(mul_tr_inp)[:, -1], mul_tr_lbl)
            loss = add_loss + mul_loss
            loss.backward()
            opt.step()
        opt.zero_grad(set_to_none=True)

    elapsed = time.time() - t0
    print(f"    Done in {elapsed:.1f}s  |  "
          f"add {add_te_as[-1]:.1%}  mul {mul_te_as[-1]:.1%}")

    return {
        "model":        model,
        "epochs":       np.array(ckpts),
        "add_tr_losses": np.array(add_tr_ls), "add_te_losses": np.array(add_te_ls),
        "add_tr_accs":   np.array(add_tr_as), "add_te_accs":   np.array(add_te_as),
        "mul_tr_losses": np.array(mul_tr_ls), "mul_te_losses": np.array(mul_te_ls),
        "mul_tr_accs":   np.array(mul_tr_as), "mul_te_accs":   np.array(mul_te_as),
        "w_norms":       np.array(w_norms),
        "elapsed":       elapsed,
    }


# ─────────────────────────────────────────────────────────────────────────────
#  FRACTION SWEEP
# ─────────────────────────────────────────────────────────────────────────────

def fraction_sweep(p, op, fracs, epochs, lr, wd, seed, device,
                   gen_thresh=0.95, d_model=64):
    """
    Train a compact model (d_model=64) for each fraction.
    Returns dict: frac → grokking epoch (or None if not reached).
    """
    print(f"\n  Fraction sweep  [{len(fracs)} fractions × {epochs:,} epochs]")
    results = {}
    for frac in fracs:
        tr, te = split_dataset(make_dataset(p, op), frac, seed)
        if not tr or not te:
            results[frac] = None; continue

        tr_inp, tr_lbl = to_tensors(tr, device)
        te_inp, te_lbl = to_tensors(te, device)
        m   = Transformer(p=p, d_model=d_model).to(device)
        opt = optim.AdamW(m.parameters(), lr=lr, weight_decay=wd, betas=(0.9, 0.98))
        sc  = optim.lr_scheduler.LambdaLR(opt, lambda s: min(s / 10, 1))

        ge  = None
        chk = max(1, epochs // 200)
        for ep in range(epochs + 1):
            if ep % chk == 0:
                m.eval()
                with torch.no_grad():
                    tea = accuracy(m(te_inp)[:, -1], te_lbl)
                if tea >= gen_thresh:
                    ge = ep; break
            if ep == epochs:
                break
            m.train()
            loss = cross_entropy(m(tr_inp)[:, -1], tr_lbl)
            loss.backward()
            # grad clipping removed — paper uses no clipping
            opt.step(); sc.step(); opt.zero_grad(set_to_none=True)

        results[frac] = ge
        status = f"grokked @ ep {ge:,}" if ge is not None else f"no grok (>{epochs:,})"
        print(f"    frac={frac:.0%}  {status}")

    return results


# ─────────────────────────────────────────────────────────────────────────────
#  DFT ANALYSIS
# ─────────────────────────────────────────────────────────────────────────────

def compute_dft(res):
    """Compute DFT power spectra of embeddings and MLP neurons."""
    p     = res["p"]
    model = _raw(res["model"])
    W_E   = model.W_E_np                           # (p, d_model)

    # All (a, op, b) pairs for the given operation
    all_data = make_dataset(p, res["op"])
    all_inp, _ = to_tensors(all_data, DEVICE)
    acts = model.get_mlp_activations(all_inp)       # (p², d_mlp)

    # Embedding DFT: along token axis
    ep_s = (np.abs(np.fft.rfft(W_E, axis=0)) ** 2).sum(axis=1)

    # MLP DFT: along a-axis, averaged over b and neurons
    grid = acts.reshape(p, p, -1)                   # (p, p, d_mlp)
    mp_s = (np.abs(np.fft.rfft(grid, axis=0)) ** 2).mean(axis=(1, 2))

    return ep_s, mp_s


# ─────────────────────────────────────────────────────────────────────────────
#  ALGORITHM ANALYSIS  (Part 5 — multiplication)
# ─────────────────────────────────────────────────────────────────────────────

def algorithm_analysis(res):
    p     = res["p"]
    model = _raw(res["model"])
    W_E   = model.W_E_np                           # (p, d_model)

    g   = primitive_root(p)
    phi = p - 1
    dl  = discrete_log_table(p, g)

    # Sort tokens 1..p-1 by discrete log
    tokens   = list(range(1, p))
    dlog_v   = np.array([dl[t] for t in tokens])
    sort_idx = np.argsort(dlog_v)
    W_sorted = W_E[np.array(tokens)[sort_idx]]     # (p-1, d_model)

    # DFT along discrete-log ordering → key frequencies in Z_{p-1}
    power_dl = (np.abs(np.fft.rfft(W_sorted, axis=0)) ** 2).sum(axis=1)

    # Cosine similarity between token embeddings
    norms    = np.linalg.norm(W_E, axis=1, keepdims=True) + 1e-8
    W_norm   = W_E / norms
    cos_sim  = W_norm @ W_norm.T                   # (p, p)

    # Cosine similarity vs. Δ discrete-log
    W_tok    = W_E[tokens] / (np.linalg.norm(W_E[tokens], axis=1, keepdims=True) + 1e-8)
    cos_sub  = W_tok @ W_tok.T                     # (p-1, p-1)
    dlog_diff= np.abs(dlog_v[:, None] - dlog_v[None, :])

    return {
        "g": g, "phi": phi, "dlog": dl,
        "dlog_v": dlog_v, "sort_idx": sort_idx,
        "norms": np.linalg.norm(W_E, axis=1),
        "power_dl": power_dl,
        "cos_sim":  cos_sim,
        "cos_sub":  cos_sub,
        "dlog_diff": dlog_diff,
        "tokens":   tokens,
    }


# ─────────────────────────────────────────────────────────────────────────────
#  FIGURE 1 — GROKKING ACCURACY + LOSS  (Part 1)
# ─────────────────────────────────────────────────────────────────────────────

def plot_part1(res, outdir):
    """
    Two-panel figure: accuracy (left) + log-loss (right).
    Blue = training, red = validation — matches the reference diagram.
    """
    p, op   = res["p"], res["op"]
    op_str  = "+" if op == OP_ADD else "×"
    eps     = res["epochs"]
    tr_acc  = res["tr_accs"]
    te_acc  = res["te_accs"]
    tr_loss = res["tr_losses"]
    te_loss = res["te_losses"]

    # Detect grokking epoch (first time test accuracy > 95%)
    gk_mask = te_acc > 0.95
    gk_ep   = eps[np.argmax(gk_mask)] if gk_mask.any() else None

    fig, axes = plt.subplots(1, 2, figsize=(14, 5), facecolor=BG)

    # ── Left: accuracy ────────────────────────────────────────────────────────
    style_ax(axes[0],
             title=f"Part 1 — Grokking Accuracy:  (a {op_str} b) mod {p}",
             xlabel="Training Epochs", ylabel="Accuracy (%)")
    axes[0].plot(eps, tr_acc * 100, color=C_TR, lw=2.3, label="Training",   zorder=3)
    axes[0].plot(eps, te_acc * 100, color=C_TE, lw=2.3, label="Validation", zorder=3)
    axes[0].set_ylim(-2, 105)
    if gk_ep is not None:
        axes[0].axvline(gk_ep, color=C_PUR, lw=1.6, ls="--", alpha=0.9,
                        label=f"Grokking ≈ ep {gk_ep:,}")
        # Annotate the large delay
        mem_ep = eps[np.argmax(tr_acc > 0.95)] if (tr_acc > 0.95).any() else eps[0]
        if gk_ep > mem_ep:
            axes[0].annotate("", xy=(gk_ep, 12), xytext=(mem_ep, 12),
                             arrowprops=dict(arrowstyle="<->", color=C_PUR, lw=1.2))
            axes[0].text((mem_ep + gk_ep) / 2, 16, "Large delay",
                         ha="center", fontsize=8, color=C_PUR)
    axes[0].legend(facecolor=CARD, labelcolor=TXT, fontsize=9, framealpha=0.9)

    # ── Right: loss (log scale) ───────────────────────────────────────────────
    style_ax(axes[1],
             title=f"Part 1 — Grokking Loss (log scale):  (a {op_str} b) mod {p}",
             xlabel="Training Epochs", ylabel="Cross-entropy loss")
    axes[1].semilogy(eps, tr_loss, color=C_TR, lw=2.3, label="Training")
    axes[1].semilogy(eps, te_loss, color=C_TE, lw=2.3, label="Validation")
    if gk_ep is not None:
        axes[1].axvline(gk_ep, color=C_PUR, lw=1.6, ls="--", alpha=0.9,
                        label=f"Grokking ≈ ep {gk_ep:,}")
    axes[1].legend(facecolor=CARD, labelcolor=TXT, fontsize=9, framealpha=0.9)

    savefig(fig, outdir / "part1_grokking.png")


# ─────────────────────────────────────────────────────────────────────────────
#  FIGURE 2 — FOURIER ANALYSIS  (Part 2)
# ─────────────────────────────────────────────────────────────────────────────

def plot_part2(res, ep_s, mp_s, outdir):
    p      = res["p"]
    op_str = "+" if res["op"] == OP_ADD else "×"
    top5e  = set(np.argsort(ep_s)[-5:].tolist())
    top5m  = set(np.argsort(mp_s)[-5:].tolist())
    fa     = np.arange(len(ep_s))

    fig, axes = plt.subplots(1, 2, figsize=(14, 5), facecolor=BG)

    # Embedding DFT
    style_ax(axes[0],
             title=f"Part 2 — Embedding DFT Power  (a {op_str} b, p={p})",
             xlabel="Frequency ω", ylabel="Σ |FFT|²  (summed over d_model)")
    bc_e = [C_TE if i in top5e else C_TR for i in fa]
    axes[0].bar(fa, ep_s, color=bc_e, width=0.85, alpha=0.9, zorder=2)
    axes[0].legend(handles=[Patch(color=C_TR, label="All frequencies"),
                             Patch(color=C_TE, label="Top-5 peaks")],
                   facecolor=CARD, labelcolor=TXT, fontsize=8)
    for i in top5e:
        axes[0].text(i, ep_s[i] * 1.02, str(i), ha="center", fontsize=7.5,
                     color=C_TE, fontweight="bold")

    # MLP DFT
    style_ax(axes[1],
             title=f"Part 2 — MLP Neuron DFT Power  (a {op_str} b, p={p})",
             xlabel="Frequency ω", ylabel="Mean |FFT|²  (avg over b × neurons)")
    bc_m = [C_MUL if i in top5m else "#34d399" for i in fa]
    axes[1].bar(fa, mp_s, color=bc_m, width=0.85, alpha=0.9, zorder=2)
    axes[1].legend(handles=[Patch(color="#34d399", label="All frequencies"),
                             Patch(color=C_MUL,    label="Top-5 peaks")],
                   facecolor=CARD, labelcolor=TXT, fontsize=8)
    for i in top5m:
        axes[1].text(i, mp_s[i] * 1.02, str(i), ha="center", fontsize=7.5,
                     color=C_MUL, fontweight="bold")

    overlap = top5e & top5m
    fig.suptitle(f"Shared dominant frequencies: ω ∈ {{{', '.join(str(f) for f in sorted(overlap))}}}  "
                 f"→ sparse Fourier basis confirmed",
                 color="#86efac", fontsize=10, y=1.01)

    savefig(fig, outdir / "part2_fourier.png")
    return top5e, top5m


# ─────────────────────────────────────────────────────────────────────────────
#  FIGURE 3 — THREE PHASES  (Part 3)
# ─────────────────────────────────────────────────────────────────────────────

def plot_part3(res, outdir):
    eps    = res["epochs"]
    tr_acc = res["tr_accs"]
    te_acc = res["te_accs"]
    tr_l   = res["tr_losses"]
    w_norm = res["w_norms"]
    wn_n   = w_norm / w_norm.max()

    def first_above(arr, thresh):
        idx = np.where(arr > thresh)[0]
        return eps[idx[0]] if len(idx) else None

    p1_end  = first_above(tr_acc, 0.95)  # train accuracy saturates → end of memorisation
    grok_ep = first_above(te_acc, 0.95)  # grokking epoch (test acc > 95%)
    p3_end  = grok_ep if grok_ep is not None else None
    last    = eps[-1]

    # Safe fallbacks for phase boundaries
    if p1_end is None: p1_end = last // 4
    if p3_end is None: p3_end = last

    phases_ep = [
        (0,      p1_end, *PHASE_COLS[0]),
        (p1_end, p3_end, *PHASE_COLS[1]),
        (p3_end, last,   *PHASE_COLS[2]),
    ]
    # Only draw cleanup phase if grokking happened
    if grok_ep is None:
        phases_ep = phases_ep[:2]

    # axs must be created BEFORE any annotation — fixed UnboundLocalError
    fig, axs = plt.subplots(4, 1, figsize=(14, 13), sharex=True, facecolor=BG)

    # Annotate grokking on train-accuracy panel now that axs exists
    if grok_ep is not None:
        axs[0].axvline(grok_ep, color=C_PUR, lw=1.8, ls="--", alpha=0.9, zorder=5,
                       label=f"Grokking ≈ ep {grok_ep:,}")
        axs[0].legend(facecolor=CARD, labelcolor=TXT, fontsize=8)

    data_rows = [
        (tr_acc * 100, C_TR,   "Train Accuracy (%)",    False),
        (te_acc * 100, C_TE,   "Test (Val.) Accuracy (%)", False),
        (tr_l,         "#93c5fd", "CE Loss (log)",       True),
        (wn_n,         C_WN,   "‖W‖²  (normalised)",    True),
    ]

    for ax, (dat, col, ylb, use_log) in zip(axs, data_rows):
        style_ax(ax, ylabel=ylb)
        fn = ax.semilogy if use_log else ax.plot
        fn(eps, dat, color=col, lw=2.3, alpha=0.95)
        yl = ax.get_ylim()
        for s, e, fc, lc, lbl in phases_ep:
            ax.axvspan(s, e, alpha=0.28, color=fc)
            mid = (s + e) / 2
            if mid < last:
                ax.text(mid, yl[0] + (yl[1] - yl[0]) * 0.84, lbl,
                        ha="center", fontsize=9, color=lc, fontweight="bold",
                        bbox=dict(fc=BG, ec="none", alpha=0.55, pad=2))

    axs[-1].set_xlabel("Epoch", color=TXT)
    grok_note = f"  (grokked @ ep {int(grok_ep):,})" if grok_ep is not None else "  (extend epochs if grokking not yet visible)"
    axs[0].set_title("Part 3 — Progress Measures: Three-Phase Grokking Decomposition" + grok_note,
                     pad=9, fontsize=11, color="#c7d2fe")

    # Phase legend
    handles = [Patch(color=c, label=l) for _, c, l in PHASE_COLS]
    axs[0].legend(handles=handles, facecolor=CARD, labelcolor=TXT, fontsize=8,
                  loc="lower right")

    savefig(fig, outdir / "part3_phases.png")


# ─────────────────────────────────────────────────────────────────────────────
#  FIGURE 4 — FRACTION SWEEP  (Part 4)
# ─────────────────────────────────────────────────────────────────────────────

def plot_part4(sweep_results, sweep_ep, p, outdir):
    fracs  = sorted(sweep_results.keys())
    ok     = [f for f in fracs if sweep_results[f] is not None]
    no     = [f for f in fracs if sweep_results[f] is None]
    eps_ok = [sweep_results[f] for f in ok]

    fig, ax = plt.subplots(figsize=(10, 5), facecolor=BG)
    style_ax(ax,
             title=f"Part 4 — Epochs Until Generalisation vs. Data Fraction  (p={p})",
             xlabel="Training data fraction",
             ylabel="Epoch of grokking (≥ 95% test accuracy)")

    if ok:
        ax.plot(ok, eps_ok, "o-", color=C_MUL, lw=2.6, ms=9, zorder=3)
        for x, y in zip(ok, eps_ok):
            ax.annotate(f"{y:,}", (x, y), textcoords="offset points",
                        xytext=(0, 12), ha="center", fontsize=9, color=TXT)

    if no:
        ax.scatter(no, [sweep_ep] * len(no),
                   marker="X", s=150, color=C_TE, zorder=4,
                   label=f"No grokking within {sweep_ep:,} epochs")
        ax.legend(facecolor=CARD, labelcolor=TXT, fontsize=9)

    ax.xaxis.set_major_formatter(
        matplotlib.ticker.FuncFormatter(lambda x, _: f"{x:.0%}"))

    # Shade the "grokking regime"
    if ok:
        ax.axvspan(min(ok), max(ok), alpha=0.07, color=C_PUR,
                   label="Grokking regime")

    savefig(fig, outdir / "part4_fraction_sweep.png")


# ─────────────────────────────────────────────────────────────────────────────
#  FIGURE 5 — ALGORITHM ANALYSIS  (Part 5)
# ─────────────────────────────────────────────────────────────────────────────

def plot_part5(aa, p, outdir):
    g, phi = aa["g"], aa["phi"]
    fig = new_fig(figsize=(16, 10))
    gs  = gridspec.GridSpec(2, 3, figure=fig, hspace=0.52, wspace=0.42)

    # ── A: cosine similarity heatmap ──────────────────────────────────────────
    ax0 = fig.add_subplot(gs[0, 0])
    style_ax(ax0, title="A — Token Embedding Cosine Similarity",
             xlabel="Token a", ylabel="Token b")
    im0 = ax0.imshow(aa["cos_sim"], cmap="RdBu_r", vmin=-1, vmax=1,
                     origin="upper", aspect="auto")
    plt.colorbar(im0, ax=ax0, fraction=0.046)

    # ── B: embedding norms sorted by discrete log ─────────────────────────────
    ax1 = fig.add_subplot(gs[0, 1])
    style_ax(ax1, title="B — Embedding Norms by Discrete-Log Order",
             xlabel="ind_g(a)  (discrete log index)", ylabel="‖W_E[a]‖")
    norms_sorted = aa["norms"][np.array(aa["tokens"])[aa["sort_idx"]]]
    ax1.bar(range(p - 1), norms_sorted, color=C_TR, alpha=0.85, width=0.85)

    # ── C: DFT along discrete-log axis ───────────────────────────────────────
    ax2 = fig.add_subplot(gs[0, 2])
    style_ax(ax2, title=f"C — DFT along Discrete-Log Axis  (Z_{{{phi}}})",
             xlabel=f"Frequency in Z_{{{phi}}}", ylabel="Σ |FFT|²")
    pw   = aa["power_dl"]
    fa   = np.arange(len(pw))
    t5dl = set(np.argsort(pw)[-5:].tolist())
    bc   = [C_TE if i in t5dl else C_MUL for i in fa]
    ax2.bar(fa, pw, color=bc, width=0.85, alpha=0.9)
    ax2.legend(handles=[Patch(color=C_MUL, label="Freq"),
                         Patch(color=C_TE,  label="Top-5")],
               facecolor=CARD, labelcolor=TXT, fontsize=8)

    # ── D: cosine similarity vs Δ discrete-log scatter ───────────────────────
    ax3 = fig.add_subplot(gs[1, 0])
    style_ax(ax3, title="D — Embedding Alignment vs. Δ Discrete-Log",
             xlabel="|ind_g(a) − ind_g(b)|", ylabel="cos(W_E[a], W_E[b])")
    ax3.hexbin(aa["dlog_diff"].flatten(), aa["cos_sub"].flatten(),
               gridsize=28, cmap="plasma", mincnt=1, alpha=0.92)
    ax3.set_facecolor(CARD)

    # ── E: learned algorithm description ─────────────────────────────────────
    ax4 = fig.add_subplot(gs[1, 1:])
    ax4.set_facecolor(CARD); ax4.axis("off")
    algo = (
        f"Part 5 — Learned Algorithm for  (a × b) mod {p}\n"
        f"{'─' * 55}\n\n"
        f"Algebraic structure:\n"
        f"  Primitive root  g = {g}    |    φ(p) = p − 1 = {phi}\n\n"
        f"Isomorphism:\n"
        f"  (Z_{{{p}}}*, ×)  ≅  (Z_{{{phi}}}, +)  via  a  ↦  ind_g(a)\n"
        f"  where  ind_g(a) = k  s.t.  {g}^k ≡ a  (mod {p})\n\n"
        f"Step 1 — Encode  (Embedding layer):\n"
        f"  embed(a)  ≈  (cos(2πω·ind_g(a)/φ),  sin(2πω·ind_g(a)/φ))\n"
        f"  for each key frequency ω  (from panel C above)\n\n"
        f"Step 2 — Combine  (Attention + MLP):\n"
        f"  compute  ind_g(a) + ind_g(b)  (mod φ = {phi})\n"
        f"  using the cosine addition formula\n\n"
        f"Step 3 — Decode  (Unembedding layer):\n"
        f"  output  =  {g}^(ind_g(a) + ind_g(b)  mod {phi})  (mod {p})\n\n"
        f"Key diagnostic:\n"
        f"  Fourier support lives in  Z_{{{phi}}}  (not Z_{{{p}}})\n"
        f"  For addition, support lives in  Z_{{{p}}}\n"
        f"  This shift from p to p−1 is the model's algebraic 'fingerprint'.\n\n"
        f"Panel D confirms: tokens with similar discrete logs\n"
        f"cluster together in embedding space — the model has\n"
        f"encoded the group structure of (Z_{{{p}}}*, ×)."
    )
    ax4.text(0.04, 0.97, algo, transform=ax4.transAxes, fontsize=9.5,
             verticalalignment="top", color="#86efac", fontfamily="monospace",
             bbox=dict(boxstyle="round,pad=0.7", fc="#070f07", ec="#1a4020", alpha=0.97))

    fig.suptitle(f"Part 5 — Algorithm Reverse-Engineering:  (a × b) mod {p}  "
                 f"via Discrete Logarithm",
                 color="#c7d2fe", fontsize=12, y=1.01)

    savefig(fig, outdir / "part5_algorithm.png")


# ─────────────────────────────────────────────────────────────────────────────
#  FIGURE 6 — CO-GROKKING  (Part 6)
# ─────────────────────────────────────────────────────────────────────────────

def plot_part6(mt, p, outdir):
    eps     = mt["epochs"]
    add_tra = mt["add_tr_accs"];  add_tea = mt["add_te_accs"]
    mul_tra = mt["mul_tr_accs"];  mul_tea = mt["mul_te_accs"]
    add_trl = mt["add_tr_losses"]; add_tel = mt["add_te_losses"]
    mul_trl = mt["mul_tr_losses"]; mul_tel = mt["mul_te_losses"]
    wn      = mt["w_norms"]

    gk_add = eps[np.argmax(add_tea > 0.95)] if (add_tea > 0.95).any() else None
    gk_mul = eps[np.argmax(mul_tea > 0.95)] if (mul_tea > 0.95).any() else None

    fig, axes = plt.subplots(2, 2, figsize=(14, 10), facecolor=BG)
    axes = axes.flatten()

    # ── Panel A: both tasks accuracy ─────────────────────────────────────────
    style_ax(axes[0], title="A — Co-Grokking: Accuracy (Both Tasks)",
             xlabel="Epoch", ylabel="Accuracy (%)")
    axes[0].plot(eps, add_tra * 100, color=C_TR,  lw=1.8, ls="--", alpha=0.7, label="Add train")
    axes[0].plot(eps, add_tea * 100, color=C_TR,  lw=2.4,          label="Add test")
    axes[0].plot(eps, mul_tra * 100, color=C_MUL, lw=1.8, ls="--", alpha=0.7, label="Mul train")
    axes[0].plot(eps, mul_tea * 100, color=C_TE,  lw=2.4,          label="Mul test")
    axes[0].set_ylim(-2, 105)
    if gk_add: axes[0].axvline(gk_add, color=C_TR,  lw=1.3, ls=":", alpha=0.85)
    if gk_mul: axes[0].axvline(gk_mul, color=C_TE,  lw=1.3, ls=":", alpha=0.85)
    axes[0].legend(facecolor=CARD, labelcolor=TXT, fontsize=8.5)

    # ── Panel B: test accuracy only — the co-grokking "clean" view ───────────
    style_ax(axes[1], title="B — Test Accuracy: Co-Grokking View",
             xlabel="Epoch", ylabel="Test Accuracy (%)")
    axes[1].plot(eps, add_tea * 100, color=C_TR,  lw=2.8, label="Addition (test)",       zorder=3)
    axes[1].plot(eps, mul_tea * 100, color=C_TE,  lw=2.8, label="Multiplication (test)", zorder=3)
    axes[1].axhline(95, color="#475569", lw=1.0, ls="--", alpha=0.7, label="95% threshold")
    axes[1].set_ylim(-2, 105)
    if gk_add and gk_mul:
        lo, hi = min(gk_add, gk_mul), max(gk_add, gk_mul)
        axes[1].axvspan(lo, hi, alpha=0.22, color=C_PUR,
                        label=f"Co-grokking window  ({hi - lo:,} ep gap)")
        axes[1].axvline(gk_add, color=C_TR,  lw=1.5, ls=":", alpha=0.9)
        axes[1].axvline(gk_mul, color=C_TE,  lw=1.5, ls=":", alpha=0.9)
    axes[1].legend(facecolor=CARD, labelcolor=TXT, fontsize=8.5)

    # ── Panel C: loss log scale ───────────────────────────────────────────────
    style_ax(axes[2], title="C — Cross-Entropy Loss (log scale)",
             xlabel="Epoch", ylabel="CE loss")
    axes[2].semilogy(eps, add_trl, color=C_TR,  lw=1.6, ls="--", alpha=0.7, label="Add train")
    axes[2].semilogy(eps, add_tel, color=C_TR,  lw=2.2,          label="Add test")
    axes[2].semilogy(eps, mul_trl, color=C_MUL, lw=1.6, ls="--", alpha=0.7, label="Mul train")
    axes[2].semilogy(eps, mul_tel, color=C_TE,  lw=2.2,          label="Mul test")
    axes[2].legend(facecolor=CARD, labelcolor=TXT, fontsize=8.5)

    # ── Panel D: weight norm ──────────────────────────────────────────────────
    style_ax(axes[3], title="D — Weight Norm ‖W‖² During Co-Grokking",
             xlabel="Epoch", ylabel="‖W‖²")
    axes[3].semilogy(eps, wn, color=C_WN, lw=2.4)
    if gk_add:
        axes[3].axvline(gk_add, color=C_TR, lw=1.5, ls=":", alpha=0.9,
                        label=f"Add groks @ ep {gk_add:,}")
    if gk_mul:
        axes[3].axvline(gk_mul, color=C_TE, lw=1.5, ls=":", alpha=0.9,
                        label=f"Mul groks @ ep {gk_mul:,}")
    axes[3].legend(facecolor=CARD, labelcolor=TXT, fontsize=8.5)

    # Overall title
    if gk_add and gk_mul:
        delta = abs(int(gk_add) - int(gk_mul))
        title_suffix = (f"  — simultaneous grok at eps {gk_add:,} / {gk_mul:,}  "
                        f"(gap = {delta:,} epochs)")
    else:
        title_suffix = "  — grokking not yet complete (increase epochs)"
    fig.suptitle(f"Part 6 — Co-Grokking: Add + Mul on p={p}" + title_suffix,
                 color="#c7d2fe", fontsize=11, y=1.01)

    savefig(fig, outdir / "part6_cogrokking.png")
    return gk_add, gk_mul


# ─────────────────────────────────────────────────────────────────────────────
#  SUMMARY PRINT
# ─────────────────────────────────────────────────────────────────────────────

def print_summary(cfg, res_add, res_mul, sweep_res, aa, gk_add, gk_mul):
    p = cfg.p
    eps_add = res_add["epochs"]
    eps_mul = res_mul["epochs"]

    gk_add_ep = eps_add[np.argmax(res_add["te_accs"] > 0.95)] \
                if (res_add["te_accs"] > 0.95).any() else "not reached"
    gk_mul_ep = eps_mul[np.argmax(res_mul["te_accs"] > 0.95)] \
                if (res_mul["te_accs"] > 0.95).any() else "not reached"

    top5e_add, top5e_mul = (set(np.argsort(res_add.get("ep_s", [0]))[-5:]),
                             set(np.argsort(res_mul.get("ep_s", [0]))[-5:]))

    print("\n" + "═" * 64)
    print("  RESULTS SUMMARY")
    print("═" * 64)
    print(f"  Prime p         : {p}  (φ(p) = {p-1})")
    print(f"  Training frac   : {cfg.frac:.0%}")
    print(f"  Epochs          : {cfg.epochs:,}")
    print(f"  Device          : {DEVICE}")
    print()
    print("  Part 1 — Grokking (Addition)")
    print(f"    Train acc      : {res_add['tr_accs'][-1]:.1%}")
    print(f"    Test  acc      : {res_add['te_accs'][-1]:.1%}")
    print(f"    Grokking epoch : {gk_add_ep}")
    print()
    print("  Part 1 — Grokking (Multiplication)")
    print(f"    Train acc      : {res_mul['tr_accs'][-1]:.1%}")
    print(f"    Test  acc      : {res_mul['te_accs'][-1]:.1%}")
    print(f"    Grokking epoch : {gk_mul_ep}")
    print()
    print("  Part 5 — Multiplication Algorithm")
    print(f"    Primitive root : g = {aa['g']}")
    print(f"    φ(p)           : {aa['phi']}")
    print(f"    Top-5 DL freqs : {sorted(set(np.argsort(aa['power_dl'])[-5:].tolist()))}")
    print()
    print("  Part 6 — Co-Grokking")
    gka_str = f"ep {gk_add:,}" if gk_add else "not reached"
    gkm_str = f"ep {gk_mul:,}" if gk_mul else "not reached"
    print(f"    Addition       : {gka_str}")
    print(f"    Multiplication : {gkm_str}")
    if gk_add and gk_mul:
        print(f"    Gap            : {abs(int(gk_add)-int(gk_mul)):,} epochs")
    print()
    print("  Fraction sweep results:")
    for frac, ep in sorted(sweep_res.items()):
        status = f"grokked @ ep {ep:,}" if ep is not None else f"no grok"
        print(f"    {frac:.0%}  →  {status}")
    print("═" * 64)


# ─────────────────────────────────────────────────────────────────────────────
#  MAIN
# ─────────────────────────────────────────────────────────────────────────────


# ─────────────────────────────────────────────────────────────────────────────
#  REPORT GENERATOR
# ─────────────────────────────────────────────────────────────────────────────

def generate_report(cfg, res_add, res_mul, sweep_res, aa, gk_add_co, gk_mul_co, outdir):
    """Write a short Markdown analysis report to the output directory."""
    p   = cfg.p
    eps = res_add["epochs"]

    gk_add_ep = eps[np.argmax(res_add["te_accs"] > 0.95)]                 if (res_add["te_accs"] > 0.95).any() else None
    gk_mul_ep = res_mul["epochs"][np.argmax(res_mul["te_accs"] > 0.95)]                 if (res_mul["te_accs"] > 0.95).any() else None

    def ep_str(v): return f"epoch {int(v):,}" if v is not None else "not reached within training"

    lines = [
        f"# Grokking of Modular Arithmetic — Analysis Report",
        f"",
        f"**Prime modulus:** p = {p}  (Nanda et al. use p=113)  |  "
        f"**Training fraction:** {cfg.frac:.0%}  |  **Epochs:** {cfg.epochs:,}  |  **WD:** {cfg.wd}  \n"
        f"*(Paper: p=113, frac=30%, epochs=40k, wd=1.0 — grokking at ~10k)*",
        f"",
        f"---",
        f"",
        f"## Part 1 — Grokking Curves",
        f"",
        f"We trained a one-layer transformer on `(a + b) mod {p}` with {cfg.frac:.0%} of all",
        f"{p}² = {p*p} pairs as training data.  The model first **memorises** the training set",
        f"(training accuracy → 100%) then, after a long delay, **generalises** to unseen pairs",
        f"— the hallmark of grokking.",
        f"",
        f"- **Grokking epoch (addition):** {ep_str(gk_add_ep)}",
        f"- **Grokking epoch (multiplication):** {ep_str(gk_mul_ep)}",
        f"",
        f"See `part1_grokking.png` for training/validation accuracy and loss curves.",
        f"",
        f"---",
        f"",
        f"## Part 2 — Sparse Fourier Basis",
        f"",
        f"Applying a 1-D DFT to the token embedding matrix (rows = token indices) and to the",
        f"post-ReLU MLP neuron activations reveals that both representations concentrate their",
        f"power on a **sparse set of frequencies** rather than spreading it uniformly.",
        f"This confirms the model implements a Fourier-based addition algorithm.",
        f"",
        f"See `part2_fourier.png` (addition) and `part2_fourier_mul.png` (multiplication).",
        f"",
        f"---",
        f"",
        f"## Part 3 — Three-Phase Decomposition",
        f"",
        f"Tracking training/test accuracy, cross-entropy loss, and weight norm jointly reveals",
        f"three distinct phases:",
        f"",
        f"1. **Memorisation** — training loss falls to near zero; test loss stays high; weights grow.",
        f"2. **Circuit Formation** — internal Fourier circuits strengthen; weight norm begins falling.",
        f"3. **Cleanup** — weight decay prunes the memorisation component; test accuracy suddenly jumps.",
        f"",
        f"See `part3_phases.png`.",
        f"",
        f"---",
        f"",
        f"## Part 4 — Data-Fraction Sweep",
        f"",
        f"We retrained with training fractions from 10 % to 90 %.  Grokking was only observed",
        f"for fractions ≥ 50 %, with the required epochs falling sharply as more data is used.",
        f"Below ~40 % the model memorises but never generalises within {cfg.sweep_epochs:,} epochs.",
        f"",
    ]
    for frac, ep in sorted(sweep_res.items()):
        status = f"grokked @ epoch {ep:,}" if ep is not None else f"no grokking"
        lines.append(f"- **{frac:.0%}** → {status}")

    lines += [
        f"",
        f"See `part4_fraction_sweep.png`.",
        f"",
        f"---",
        f"",
        f"## Part 5 — Algorithm Reverse-Engineering (Multiplication)",
        f"",
        f"For `(a × b) mod {p}`, the model exploits the isomorphism",
        f"(Z_{p}*, ×) ≅ (Z_{p-1}, +) via discrete logarithms (primitive root g = {aa['g']}).",
        f"",
        f"**Learned algorithm:**",
        f"1. **Embed** each token a as Fourier features of its discrete log: cos(2πω·log_g(a)/(p−1)).",
        f"2. **Combine** using the cosine addition formula to compute log_g(a) + log_g(b) mod (p−1).",
        f"3. **Decode** the sum back to g^(log_g(a)+log_g(b)) mod p via the unembedding layer.",
        f"",
        f"The DFT of embeddings sorted by discrete-log order shows dominant frequencies in Z_{p-1},",
        f"not Z_{p} — this algebraic fingerprint distinguishes multiplication from addition.",
        f"",
        f"See `part5_algorithm.png`.",
        f"",
        f"---",
        f"",
        f"## Part 6 — Co-Grokking",
        f"",
        f"A single model trained simultaneously on addition **and** multiplication shows",
        f"**co-grokking**: both tasks generalise at approximately the same time, suggesting",
        f"shared internal representations underlie the two modular arithmetic algorithms.",
        f"",
        f"- Addition grokked:       {ep_str(gk_add_co)}",
        f"- Multiplication grokked: {ep_str(gk_mul_co)}",
        f"",
        f"See `part6_cogrokking.png`.",
        f"",
        f"---",
        f"*Report auto-generated by the Grokking Analysis Suite.*",
    ]

    report_path = outdir / "REPORT.md"
    report_path.write_text("\n".join(lines))
    print(f"    Report → {report_path}")


def main():
    cfg = get_config()
    random.seed(cfg.seed)
    np.random.seed(cfg.seed)
    torch.manual_seed(cfg.seed)

    outdir = Path(cfg.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    use_amp = not cfg.no_amp

    print("\n" + "═" * 64)
    print("  Grokking of Modular Arithmetic — Full Analysis")
    print("═" * 64)
    print(f"  Prime p       : {cfg.p}  (Nanda et al. use 113; 67 is our distinct prime)")
    print(f"  Training frac : {cfg.frac:.0%}  ({int(cfg.frac * cfg.p**2):,} / {cfg.p**2:,} pairs)")
    print(f"  Epochs        : {cfg.epochs:,}")
    print(f"  d_model       : {cfg.d_model}")
    print(f"  LR / WD       : {cfg.lr} / {cfg.wd}")
    print(f"  Paper ref     : Nanda et al. ICLR 2023 — p=113, frac=0.30, wd=1.0, 40k epochs")
    print(f"  Our config    : p={cfg.p}, frac={cfg.frac:.0%}, wd={cfg.wd}, {cfg.epochs:,} epochs")
    print(f"  Note          : grokking for p=67 expected ~10-20k epochs with wd={cfg.wd}")
    print(f"  Co-grok WD    : {cfg.cogrok_wd}  (needs wd>=2.5 for dual-circuit cleanup)")
    print(f"  Co-grok epochs: {cfg.cogrok_epochs:,}")
    print(f"  Co-grok frac  : {cfg.cogrok_frac:.0%}  (mul nonzero pairs only)")
    print(f"  Output dir    : {outdir.resolve()}")
    print_device()
    print("─" * 64)

    # ──────────────────────────────────────────────────────────────────────────
    #  PART 1 + 2 + 3 — Addition
    # ──────────────────────────────────────────────────────────────────────────
    print("\n▶ PART 1/2/3 — Addition (a + b) mod p")
    res_add = train(cfg.p, OP_ADD, cfg.frac, cfg.epochs, cfg.lr, cfg.wd,
                    cfg.d_model, cfg.seed, DEVICE, use_amp=use_amp)

    ep_s_add, mp_s_add = compute_dft(res_add)
    res_add["ep_s"] = ep_s_add

    print("\n  Plotting Part 1 (grokking curves)...")
    plot_part1(res_add, outdir)

    print("  Plotting Part 2 (Fourier analysis)...")
    top5e_add, top5m_add = plot_part2(res_add, ep_s_add, mp_s_add, outdir)

    print("  Plotting Part 3 (three phases)...")
    plot_part3(res_add, outdir)

    # ──────────────────────────────────────────────────────────────────────────
    #  PART 4 — Fraction Sweep
    # ──────────────────────────────────────────────────────────────────────────
    print("\n▶ PART 4 — Data Fraction Sweep")
    # Fraction sweep — matches Nanda et al. Fig 20/21 range
    fracs      = [0.10, 0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90]
    sweep_res  = fraction_sweep(cfg.p, OP_ADD, fracs, cfg.sweep_epochs,
                                cfg.lr, cfg.wd, cfg.seed, DEVICE)
    print("  Plotting Part 4 (fraction sweep)...")
    plot_part4(sweep_res, cfg.sweep_epochs, cfg.p, outdir)

    # ──────────────────────────────────────────────────────────────────────────
    #  PART 5 — Multiplication + Algorithm Reverse-Engineering
    # ──────────────────────────────────────────────────────────────────────────
    print("\n▶ PART 5 — Multiplication + Algorithm Reverse-Engineering")
    res_mul = train(cfg.p, OP_MUL, cfg.frac, cfg.epochs, cfg.lr, cfg.wd,
                    cfg.d_model, cfg.seed, DEVICE, use_amp=use_amp)

    ep_s_mul, mp_s_mul = compute_dft(res_mul)
    res_mul["ep_s"] = ep_s_mul

    # Also plot a DFT figure for multiplication
    print("  Plotting Part 2 (Fourier, multiplication)...")
    plot_part2(res_mul, ep_s_mul, mp_s_mul,
               outdir)  # overwrites with mul; rename if you want both
    (outdir / "part2_fourier.png").rename(outdir / "part2_fourier_mul.png")
    # Re-plot addition DFT under the original name
    plot_part2(res_add, ep_s_add, mp_s_add, outdir)

    print("  Running algorithm analysis...")
    aa = algorithm_analysis(res_mul)

    print("  Plotting Part 5 (algorithm)...")
    plot_part5(aa, cfg.p, outdir)

    # ──────────────────────────────────────────────────────────────────────────
    #  PART 6 — Co-Grokking
    # ──────────────────────────────────────────────────────────────────────────
    print("\n▶ PART 6 — Co-Grokking (Addition + Multiplication)")
    # Co-grokking uses dedicated epochs/wd — see get_config() for rationale
    print(f"  Co-grokking: epochs={cfg.cogrok_epochs:,}  wd={cfg.cogrok_wd}  frac={cfg.cogrok_frac:.0%}")
    print(f"  Single-task: epochs={cfg.epochs:,}  wd={cfg.wd}  frac={cfg.frac:.0%}")
    print(f"  Mul uses nonzero pairs — required for discrete-log grokking")
    mt = train_multitask(cfg.p, cfg.cogrok_frac, cfg.cogrok_frac,
                         cfg.cogrok_epochs, cfg.cogrok_lr, cfg.cogrok_wd,
                         cfg.cogrok_d_model, cfg.seed, DEVICE, use_amp=use_amp)

    print("  Plotting Part 6 (co-grokking)...")
    gk_add_co, gk_mul_co = plot_part6(mt, cfg.p, outdir)

    # ──────────────────────────────────────────────────────────────────────────
    #  SUMMARY
    # ──────────────────────────────────────────────────────────────────────────
    print_summary(cfg, res_add, res_mul, sweep_res, aa, gk_add_co, gk_mul_co)

    print("\n  Generating Markdown report...")
    generate_report(cfg, res_add, res_mul, sweep_res, aa, gk_add_co, gk_mul_co, outdir)

    print(f"\n  All figures saved to:  {outdir.resolve()}/")
    for f in sorted(outdir.glob("*.png")):
        print(f"    {f.name}")
    print()

    # Try to display images inline if running in a notebook (e.g., Colab)
    try:
        from IPython.display import Image, display
        if get_ipython() is not None:
            print("  Displaying figures inline (Notebook environment detected):")
            for f in sorted(outdir.glob("*.png")):
                display(Image(filename=str(f)))
    except (ImportError, NameError):
        pass


if __name__ == "__main__":
    main()